[package]
name = "tl-to-json"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

[dependencies]
grammers-tl-parser = { path = "../../lib/grammers-tl-parser", version = "1.0.0" }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
